name: 'AlliedPayment artifactory Actions'
description: 'Runs artifactory commands via GitHub Actions.'
author:  'AlliedPayment'
branding:
  icon: 'cloud'
  color: 'purple'
inputs:
  sha: 
    description: 'sha to find'
    required: true 
  branch:
    description: 'branch to find'
    required: false
  branches:
    description: 'branches to find'
    required: false  
outputs:
    build-version:
      description: 'The version found in artifactory'
    branch:
      description: 'The branch found in artifactory'
    pr:
      description: 'The pr found in artifactory (if any)'
runs:
  using: 'docker'
  image: './Dockerfile'
